package cn.edu.zzia.bookstore.domain;
// Generated 2017-3-10 14:17:41 by Hibernate Tools 3.4.0.CR1

/**
 * Book generated by hbm2java
 */
@SuppressWarnings("serial")
public class Book implements java.io.Serializable {

	private String id;
	private Category category;
	private Publisher publisher;
	private String name;
	private String author;
	private double price;
	private String image;
	private String description;

	public Book() {
	}

	public Book(String id, String name, String author, double price) {
		this.id = id;
		this.name = name;
		this.author = author;
		this.price = price;
	}

	public Book(String id, Category category, String name, String author, double price, String image,
			String description) {
		this.id = id;
		this.category = category;
		this.name = name;
		this.author = author;
		this.price = price;
		this.image = image;
		this.description = description;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	public double getPrice() {
		return this.price;
	}

	public void setPrice(double price) {
		this.price = price;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Publisher getPublisher() {
		return publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

}
