package cn.edu.zzia.bookstore.domain;
// Generated 2017-3-10 14:17:41 by Hibernate Tools 3.4.0.CR1

/**
 * Category generated by hbm2java
 */
@SuppressWarnings("serial")
public class Category implements java.io.Serializable {

	private String id;
	private String name;
	private String description;

	public Category() {
	}

	public Category(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public Category(String id, String name, String description) {
		this.id = id;
		this.name = name;
		this.description = description;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
