package cn.edu.zzia.bookstore.domain;
// Generated 2017-3-10 14:17:41 by Hibernate Tools 3.4.0.CR1

/**
 * Orderitem generated by hbm2java
 */
@SuppressWarnings("serial")
public class Orderitem implements java.io.Serializable {

	private String id;
	private Order order;
	private Book book;
	private Integer quantity;
	private Double price;

	public Orderitem() {
	}

	public Orderitem(String id) {
		this.id = id;
	}

	public Orderitem(String id, Order orders, Book book, Integer quantity, Double price) {
		this.id = id;
		this.order = orders;
		this.book = book;
		this.quantity = quantity;
		this.price = price;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public Order getOrder() {
		return order;
	}

	public void setOrder(Order order) {
		this.order = order;
	}

	public Book getBook() {
		return this.book;
	}

	public void setBook(Book book) {
		this.book = book;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}
}
