package cn.edu.zzia.bookstore.domain;
// Generated 2017-3-10 14:17:41 by Hibernate Tools 3.4.0.CR1

/**
 * Privilege generated by hbm2java
 */
@SuppressWarnings("serial")
public class Privilege implements java.io.Serializable {

	private String id;
	private String name;

	public Privilege() {
	}

	public Privilege(String id) {
		this.id = id;
	}

	public Privilege(String id, String name) {
		this.id = id;
		this.name = name;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
