package cn.edu.zzia.bookstore.domain;
// Generated 2017-3-13 11:22:10 by Hibernate Tools 3.4.0.CR1

/**
 * Publisher generated by hbm2java
 */
@SuppressWarnings("serial")
public class Publisher implements java.io.Serializable {

	private String id;
	private String publisherName;
	private String description;

	public Publisher() {
	}

	public Publisher(String id) {
		this.id = id;
	}

	public Publisher(String id, String publisherName, String description) {
		this.id = id;
		this.publisherName = publisherName;
		this.description = description;
	}

	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getPublisherName() {
		return this.publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
